### ISSUE TITLE
support page changes

### ISSUE THREAD

**Issue by ayeshare** [debrief/debrief.github.io#10]
In support page, "learn more" links have to be fixed.
![image](https://user-images.githubusercontent.com/38917949/88286847-06c50480-cd0f-11ea-995f-1f5f6c49b447.png)

**Comment by IanMayo** [comment]
@ayeshare - aren't you able to insert/correct the anchors on the support page?

**Comment by ayeshare** [comment]
@IanMayo I dont know what the anchors should be

**Comment by ayeshare** [comment]
@IanMayo The anchors are fixed now.

**Comment by IanMayo** [comment]
Great, thanks @ayeshare
